//
// Created by volha on 10/12/2021.
//

#ifndef PRCPP_1SEM_09_UNITTESTING_DEMOGOOGLETEST_SRC_ARITHMETICLIB_H_
#define PRCPP_1SEM_09_UNITTESTING_DEMOGOOGLETEST_SRC_ARITHMETICLIB_H_

int Factorial(int n);

#endif // PRCPP_1SEM_09_UNITTESTING_DEMOGOOGLETEST_SRC_ARITHMETICLIB_H_
