//
// Created by volha on 19.10.2019.
//

#ifndef COUNTRIESPOPULATION__PROGRAMCOUNTRIESPOPULATION_H_
#define COUNTRIESPOPULATION__PROGRAMCOUNTRIESPOPULATION_H_

class ProgramCountriesPopulation {
public:
    static int Main();
};

#endif // COUNTRIESPOPULATION__PROGRAMCOUNTRIESPOPULATION_H_
